CREATE  TABLE PUBLIC.CLIENT(
ID BINARY(255) NOT NULL PRIMARY KEY,
EMAIL VARCHAR(255),
FIO VARCHAR(255),
PASSPORT_NUMBER VARCHAR(255),
TELEPHONE_NUMBER VARCHAR(255),
UNIQUE(EMAIL),
UNIQUE(PASSPORT_NUMBER),
UNIQUE(TELEPHONE_NUMBER)
)
CREATE  TABLE PUBLIC.CREDIT(
ID BINARY(255) NOT NULL PRIMARY KEY,
CREDIT_LIMIT BIGINT,
CREDIT_PERCENT DOUBLE
)
CREATE  TABLE PUBLIC.BANK(
ID BINARY(255) NOT NULL PRIMARY KEY
)
CREATE  TABLE PUBLIC.BANK_CLIENT_LIST(
BANK_ID BINARY(255) NOT NULL,
CLIENT_LIST_ID BINARY(255) NOT NULL,
PRIMARY KEY(BANK_ID,CLIENT_LIST_ID),
FOREIGN KEY(BANK_ID) REFERENCES PUBLIC.BANK(ID),
FOREIGN KEY(CLIENT_LIST_ID) REFERENCES PUBLIC.CLIENT(ID)
)
CREATE  TABLE PUBLIC.BANK_CREDIT_LIST(
BANK_ID BINARY(255) NOT NULL,
CREDIT_LIST_ID BINARY(255) NOT NULL,
PRIMARY KEY(BANK_ID,CREDIT_LIST_ID),
FOREIGN KEY(BANK_ID) REFERENCES PUBLIC.BANK(ID),
FOREIGN KEY(CREDIT_LIST_ID) REFERENCES PUBLIC.CREDIT(ID)
)
CREATE  TABLE PUBLIC.CREDIT_OFFER(
ID BINARY(255) NOT NULL PRIMARY KEY,
CREDIT_SUM NUMERIC(19,2),
CLIENT_ID BINARY(255) NOT NULL,
CREDIT_ID BINARY(255) NOT NULL,
FOREIGN KEY(CLIENT_ID) REFERENCES PUBLIC.CLIENT(ID),
FOREIGN KEY(CREDIT_ID) REFERENCES PUBLIC.CREDIT(ID)
)
CREATE  TABLE PUBLIC.PAYMENT_SCHEDULE(
ID BINARY(255) NOT NULL PRIMARY KEY,
CREDIT_BODY_SUM NUMERIC(19,2),
CREDIT_PERCENT_SUM NUMERIC(19,2),
PAYMENT_DATE DATE,
PAYMENT_SUM NUMERIC(19,2),
OFFER_ID BINARY(255),
FOREIGN KEY(OFFER_ID) REFERENCES PUBLIC.CREDIT_OFFER(ID)
)